### ISSUE TITLE
Request to change behaviour of muted applications

### ISSUE THREAD

**Issue by WhosyVox** [Aurailus/Myxer#2]
Currently when an application is muted, the entire meter control is disabled. This is not always obvious on some themes.
A muted application also behaves differently from one set to 0% volume when, in practice, this is effectively the same state.

I request that rather than the control be disabled on mute, the display state is set to 0% volume but the control is still left enabled.
From this point pressing the mute/un-mute button would return the application to its previous volume level. Additionally simply moving the volume slider above 0% should also effectively 'un-mute' the application.

**Comment by Aurailus** [comment]
I really like this behavior, I'll work towards implementing it.

**Comment by Aurailus** [comment]
This behavior has now been implemented! Closing.
