### ISSUE TITLE
Consider implementing rustdoc code comments for documentation

### ISSUE THREAD

**Issue by WhosyVox** [Aurailus/Myxer#3]
Rust comes with a utility called 'rustdoc' which would allow for the programmatic generation of documentation for your project.
It can be called with `cargo doc` to generate initial documentation into the `target` directory, including documentation of imported libraries.
It is recommended you add comment blocks before type/struct/method definitions in order to better document the code.

See:
https://doc.rust-lang.org/reference/comments.html
https://doc.rust-lang.org/rustdoc/index.html

**Comment by Aurailus** [comment]
Thanks for the push to get this done, and for the info provided. I've now documented every method and struct, as of 173072e4f89ae09054dd332486a151ce9c713af3.
