### ISSUE TITLE
Publishing this application to Nixpkgs

### ISSUE THREAD

**Issue by rster2002** [Aurailus/Myxer#30]
Hi!

I've wanted to install your application on my machine using Nix and noticed it was not yet published. Nix is a bit _quirky_ when it comes to packages so you can't just install any dynamically linked binary. If it's alright with you I would like to put some work into getting it into nixpkgs.

I've already tested locally and from what I can see if you would want this these are the steps:
- [x] Still need to finalize the nix configuration, but wanted to check your interest in this first. Functionally it works, but just needs to fix some of the meta data like author etc.
- [x] Create a new release tag. For some reason when using the current latest tag it complains about an empty version tag for `gio`, but not when I clone the repo directly.
- [x] Merge the `default.nix` configuration into the https://github.com/NixOS/nixpkgs repository with the new tag.

After that it should be available for anyone using nixpkgs.

Let me know if you're interested in doing this.

**Comment by Aurailus** [comment]
Hey @rster2002, thanks for the interest in this project!
I'd be happy to have Myxer available on Nix. I don't have much time to dedicate to this project right now to work on it myself, but if you're able to make a Pull Request with the required changes, I'd be happy to merge them into the project.
I wasn't aware that the GIO dependency was still out of date in the latest release, I've just merged in some changes in another PR and created a new release with that fixed, so all should be good there. 1.3.0 should be good to go if you'd like to take this on.
Thanks! Feel free to ping me if you have any questions.

**Comment by ErinvanderVeen** [comment]
I previously maintained the Myxer package in Nixpkgs, but the package was removed after Myxer's build was broken with the patch not being merged for a few months.

Here you can find the original Nix expression that was part of Nixpkgs:
https://github.com/ErinvanderVeen/nixpkgs/blob/d7a24478a32e7ce72367d39cd7c53a0fea2e2a22/pkgs/applications/audio/myxer/default.nix

Good luck.

**Comment by rster2002** [comment]
Thanks for the encouragement! Working on it right now. I'm adding myself as a maintainer on the nixpkg, but should I keep you on there as well of should I remove you @ErinvanderVeen?

**Comment by rster2002** [comment]
Myxer is now available on the unstable branch on Nix: https://search.nixos.org/packages?channel=unstable&from=0&size=50&sort=relevance&type=packages&query=Myxer

**Comment by Aurailus** [comment]
Thank you so much! I'll put in effort to merge changes more quickly in the future. Things have just been really rough for me these last few months.

**Comment by rster2002** [comment]
No worries at all! Life can be tough enough as it is without also maintaining projects. Already installed it on my machine and it's wonderful!
