### ISSUE TITLE
Consider using Rustfmt

### ISSUE THREAD

**Issue by pirak** [Aurailus/Myxer#4]
I tried to run [clippy](https://github.com/rust-lang/rust-clippy) to find potential small improvements I could contribute.
However, as hard tabs are used instead of spaces a lot of [`tabs_in_doc_comments`](https://rust-lang.github.io/rust-clippy/master/index.html#tabs_in_doc_comments) issues are listed which makes it hard to find useful hints.

Using [rustfmt](https://github.com/rust-lang/rustfmt) the whole code can be formatted easily and in a way that is used for most other Rust projects.

## Alternative
If you prefer to keep tabs, you could add a [`rustfmt.toml`](https://rust-lang.github.io/rustfmt/) with
```toml
hard_tabs = true
```
To suppress the mentioned clippy warning, then `#![allow(clippy::tabs_in_doc_comments)]` should be added somewhere at the top of `main.rs`.

**Comment by elkowar** [comment]
Please do switch to using rustfmt, it makes development a lot more comfortable - and especially makes it more comfortable when people start contributing to your project. people have the weirdest formatting concepts when not forced through an autoformatter, otherwise,....

**Comment by Aurailus** [comment]
Thanks for the suggestion! I've never looked at this tool, but I'll try configuring it today. :)

**Comment by Aurailus** [comment]
As of right now, I'm not going to use `rustfmt`. I looked through its options and was unable to find settings for several syntax choices that I consider important, some other options were locked behind the nightly channel. It's possible that I might be able to use it once the tool matures a little more.
